databases:
  - name: siplog
    databaseName: siplog
    plan: free
    user: siplog

services:
  - type: web
    name: siplog
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: siplog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
